---
title: "Courses"
author: "Bioinformatics"
output: html_document
---

### Fall 2017 term courses:

BIOF309 | Introduction to Python

BIOF312 | Introduction to Perl

BIOF339 | Practical R

BIO501 | Introduction to R: Step-by-Step Guide (7 weeks)

BIOF509 | Machine Learning and Object-Oriented Programming with Python

BIOF518 | Theoretical and Applied Bioinformatics

BIOF525 | Computational Approaches to Metagenomics (8 weeks)

MATH127 | Elementary Calculus I

MATH215 | Introduction to Linear Algebra With Applications in Statistics

STAT200 | Experimental Statistics I

STAT317 | Introduction to Epidemiology (Online)

STAT321 | Methodology in Clinical Trials

STAT500 | Statistics for Biomedical Scientists I

STAT500 II - O | Statistics for Biomedical Scientists II (Online)
 

## Spring 2018 term courses:

BIOF309 | Introduction to Python

BIOF395 | Introduction to Text Mining

BIOF450 | Computational Biology and Evolutionary Genomics

BIOF475 | Introduction to New Technologies in Data Science

BIOF509 | Machine Learning and Object-Oriented Programming with Python

BIOF521 | Bioinformatics for Analysis of Data Generated by Next Generation Sequencing

BIOF529 | Super R with Shiny!

MATH128 | Elementary Calculus II

STAT200 | Experimental Statistics II

STAT325 - O | Epidemiologic Research Methods (Online)

STAT330 | Introduction to SAS - Statistical Analysis System (10 weeks)

STAT500 | Statistics for Biomedical Scientists II

STAT500 I - O | Statistics for Biomedical Scientists I (Onlin
